### ISSUE TITLE
Circular buffer recording

### ISSUE THREAD

**Issue by cedricve** [dridri/OpenMaxIL-cpp#3]
Would be nice to have a circular buffer while recording, any idea of this would fit in your repo?  eg keeping 5 seconds before now in memory.

**Comment by dridri** [comment]
A simple implementation would be to use an std::list, using `emplace_back()` to append new buffers, and `front()` / `pop_front()` to take/remove old ones.
I will take a look if it is possible to add this feature hidden behind `getOutputData()`

**Comment by cedricve** [comment]
nice! I was thinking about it (queue principal) but was a bit worried about the performance. Thanks for your advice.

**Comment by dridri** [comment]
What do you have in mind exactly when talking about circular buffer here ?

edit: about performance, STL classes are supposed to be very well optimized

**Comment by cedricve** [comment]
exactly what you propose:

1. Having a data structure which keeps x seconds of video in memory. (On each loop, pop first frame and append new frame).
2. When starting a new record (video surveilance: motion detected), it will start recording but also prepend the x seconds video (in memory).

**Comment by dridri** [comment]
Ah okay, so the main purpose is to be able to grab previous frames when the recording starts "too late"

**Comment by cedricve** [comment]
exactly.

**Comment by cedricve** [comment]
hey @dridri, I have ended up creating a LIFO queue class of preferable size (e.g. 30). In the record thread I add images to the queue, and remove the last one. When a recording starts I empty and write out the queue before the actual recording.

As this involves a lot of memcpy's this is a heavy operation, so I was wondering if you see a better way to resolve this?

**Comment by dridri** [comment]
Sadly I don't see any other solution...

**Comment by cedricve** [comment]
Ok no problem, thanks for your advice. I'll close this ticket, and reopen if I might find a more performant solution.
