### ISSUE TITLE
crash  OMX Error 80001000

### ISSUE THREAD

**Issue by natxopedreira** [dridri/OpenMaxIL-cpp#6]
Hello

Im using your library (thanks!) in a 12H per day situation to capture video using an auvidea card, seems to work ok but im getting ocasional crash in the app, i have a snapshot of the terminal and maybe you can give me some clues of whats happening??

The error im getting is OMX Error 80001000

https://imgur.com/a/a9qp3

Thanks!

**Comment by dridri** [comment]
0x80001000 means "OMX_ErrorInsufficientResources", you could try to increase gpu_mem in your /boot/config.txt

**Comment by natxopedreira** [comment]
Thanks!!!

I have 512 to my GPU

I think found the issue.... 

I get that error, if the hdmi cable to the capture card lost contact while capturing or if the cable its not present on startup.

So as a workaround i set in component.cpp SetState wait=false so if the cable moves the app continue and i get black from the capture card. Which i prefer.

I will have some problem with the library setting this wait to false ????

I have to say thanks again for your library, i tried others to use with the auvidea capture card and yours seem to be the best and more stable one!!!!

**Comment by dridri** [comment]
ah, happy to know that you found the origin of your issue.
I added the wait parameter to SetState exactly for this kind of situation, so you can set it to false without any problems.

**Comment by natxopedreira** [comment]
Good to know !

I will post back here if "not stable" or another problem, thanks for your help
